repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-yaml
        exclude: mkdocs.yaml
      - id: end-of-file-fixer
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/astro/deadnix
    rev: v1.3.0
    hooks:
      - id: deadnix
        stages: [pre-commit]
  - repo: https://github.com/kamadorueda/alejandra
    rev: 4.0.0
    hooks:
      - id: alejandra-system
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint-fix
        args:
          - --disable
          - MD013
  - repo: local
    hooks:
      - id: zola-check
        name: zola check
        entry: bash -c 'cd src && zola check'
        language: system
        pass_filenames: false
        description: 'Runs zola check command on the repository'
