# The URL the site will be built for
base_url = "https://alillelund.github.io"

# The site title and description; used in feeds by default.
title = "alillelund"
description = "My personal blog - and experimental repo on all git related interest projects"

# The default language; used in feeds.
default_language = "en"

# Theme
theme = "duckquill"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "solarized-dark", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" },
]

[extra]
# Put all your custom variables here
default_theme = "light"
#
# Sets theme and browser theme color.
# See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
accent_color = "#ff7800"
# Ditto but for the dark theme.
# If not set regular variant will be used.
accent_color_dark = "#ffa348"

[extra.nav]
# Whether to automatically hide nav when not hovered or focused
# auto_hide = true
# Whether to show the manual theme switcher in the nav
show_theme_switcher = true
# Whether to show the link to the source repository in the nav
show_repo = true
# Links used in the nav.
# For local files use same link format as in Markdown,
# i.e. "@/blog/_index.md".
# See https://www.getzola.org/documentation/content/linking/#internal-links
links = [
  # {url = "https://codeberg.org/daudix/duckquill", name = "Repo"},
  #  {url = "$BASE_URL/demo", name = "Demo"},
  { url = "@/praktisk-info/_index.md", name = "Praktisk Info" },
]
