# The URL the site will be built for
base_url = "https://alillelund.github.io"

# The site title and description; used in feeds by default.
title = "alillelund"
description = "My personal blog - and experimental repo on all git related interest projects"

# The default language; used in feeds.
default_language = "en"

# Theme
theme = "duckquill"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
default_theme = "light"

[extra.nav]
# Whether to automatically hide nav when not hovered or focused
# auto_hide = true
# Whether to show the manual theme switcher in the nav
show_theme_switcher = true
# Whether to show the link to the source repository in the nav
show_repo = true
# Links used in the nav.
# For local files use same link format as in Markdown,
# i.e. "@/blog/_index.md".
# See https://www.getzola.org/documentation/content/linking/#internal-links
links = [
  # {url = "https://codeberg.org/daudix/duckquill", name = "Repo"},
  #  {url = "$BASE_URL/demo", name = "Demo"},
  { url = "@/praktisk-info/_index.md", name = "Praktisk Info" },
]
